- bucket: !!binary |
    Z0FBQUFBQmFUTGJHdGstMWlIaTdfNGZGdlhhSzdyRUJUdWRicmtnRU40RVVIMlVWZ0l2aXhFdUxo
    X2M4cldjS0pyaHFVMFRSRTFHbzZTdGpqSTlmdGZCZWZoWE5QaktVXzROMmR4VDVHUEExeF9hSG5f
    RWZiZTQ9
  date: '2018-01-03T10:55:42.854Z'
  email: 27b6f3ebc1535b4b11b1508ec7c7364c
  message: من یه دامنه و هاست دارم که به هم متصل بودن، تصورم این بود که میشه مثل CloudFlare
    این Netlify رو بین این دو قرار بدم، وارد Netlify شدم و دامنم رو به DNS Zone اضافه
    کردم، چهار تا NameServer داد که دامنم روی اونا تنظیم کردم، بعد تو Netlify اومدم
    توی قسمت DNS Records دو تا NameServer هاستم رو در قالب  NS وارد کردم، الان بعد
    یه روز دامنم به هاست متصل نمیشه. نمیدونم ایراد کارم کجاست؟
  name: روح اله
  page_date: 2017-12-16 00:00:00 +0100
  page_id: /netlify
  page_title: فعالسازی HTTPS به کمک Netlify
  page_uuid: df8977bd-9a2f-4ef7-9e9f-49459afefb71
  website: ''
