- bucket: !!binary |
    Z0FBQUFBQmFUTGJHdGstMWlIaTdfNGZGdlhhSzdyRUJUdWRicmtnRU40RVVIMlVWZ0l2aXhFdUxo
    X2M4cldjS0pyaHFVMFRSRTFHbzZTdGpqSTlmdGZCZWZoWE5QaktVXzROMmR4VDVHUEExeF9hSG5f
    RWZiZTQ9
  date: '2018-01-03T10:55:42.854Z'
  email: 27b6f3ebc1535b4b11b1508ec7c7364c
  message: من یه دامنه و هاست دارم که به هم متصل بودن، تصورم این بود که میشه مثل CloudFlare
    این Netlify رو بین این دو قرار بدم، وارد Netlify شدم و دامنم رو به DNS Zone اضافه
    کردم، چهار تا NameServer داد که دامنم روی اونا تنظیم کردم، بعد تو Netlify اومدم
    توی قسمت DNS Records دو تا NameServer هاستم رو در قالب  NS وارد کردم، الان بعد
    یه روز دامنم به هاست متصل نمیشه. نمیدونم ایراد کارم کجاست؟
  name: روح اله
  page_date: 2017-12-16 00:00:00 +0100
  page_id: /netlify
  page_title: فعالسازی HTTPS به کمک Netlify
  page_uuid: df8977bd-9a2f-4ef7-9e9f-49459afefb71
  website: ''
- bucket: !!binary |
    Z0FBQUFBQmFUUGxhcjd1bVNURlg1bUZaeFVZSnp5MWI0VXV3aWFaWUY1bERDNDFSTXlKVjJYa0hZ
    ZnpXTjNzS0pOcU0yMlFUd05pYUVhMnk0czBEUU1FWmpZUlpiNFhOekhJcFdtaUQxNjZFeFQzQTlp
    ZzU3S3M9
  date: '2018-01-03T15:39:47.386Z'
  email: 0371f5b900b484368f9e1717d7d965b1
  message: "> تصورم این بود که میشه مثل CloudFlare این Netlify رو بین این دو قرار\
    \ بدم\r\n\r\nنتلیفای سایت دیگه‌ای رو نمی‌تونه سرو کنه. همه چیز باید رو خودش باشه.\
    \ مناسب سایتهای استاتیکه.\r\n\r\n> بعد تو Netlify اومدم توی قسمت DNS Records دو\
    \ تا NameServer هاستم رو در قالب NS وارد کردم\r\n\r\nاین قسمت فقط به درد تعریف\
    \ رکوردهای جدید می‌خوره. مثلا تعریف زیر دامنه برای ایمیل. نمی‌تونی هاستت خودت\
    \ رو اینجا وارد کنی.\r\n\r\nکلا نمی‌تونی از نتلیفای برای اضافه کردن https به سرور\
    \ یا هاست شخصی خودت استفاده کنی مگر اینکه استاتیک باشه و کاملا از روی نتلیفای\
    \ سرو بشه. مطلب رو اصلاح می‌کنم که باعث سردرگمی نشه."
  name: مهدی صادقی
  page_date: 2017-12-16 00:00:00 +0100
  page_id: /netlify
  page_title: فعالسازی HTTPS به کمک Netlify
  page_uuid: df8977bd-9a2f-4ef7-9e9f-49459afefb71
  website: https://mehdix.ir
